- name: Preparatory steps for all Gerrit build jobs
  hosts: all
  roles:
    - ensure-bazelisk
    - ensure-java
    - role: ensure-java
      java_version: 17
    - role: ensure-nodejs
      node_version: 12
    - install-build-essential
    - prepare-gerrit-repos
