- name: Preparatory steps for all Gerrit build jobs
  hosts: all
  roles:
    - ensure-bazelisk
    - ensure-java
    - role: install-nodejs
      node_version: 10
    - install-build-essential
    - prepare-gerrit-repos
