- name: Preparatory steps for all Gerrit build jobs
  hosts: all
  roles:
    - ensure-bazelisk
    - role: ensure-java
      java_version: 11
    - role: ensure-nodejs
      node_version: 10
    - install-build-essential
    - prepare-gerrit-repos
