- name: Run bazelisk build
  shell: |
    java -fullversion
    {{ bazelisk_executable }} version
    {{ bazelisk_executable }} build --spawn_strategy=standalone --genrule_strategy=standalone {{ bazelisk_targets }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_user_dir }}/src/gerrit.googlesource.com/gerrit"
