- name: Preparatory steps for gitiles build job
  hosts: all
  roles:
    - ensure-bazelisk
      bazelisk_version: v1.28.1
    - role: ensure-java
      java_version: 17
    - install-build-essential
    - prepare-gerrit-repos
