- project:
    check:
      jobs:
        - test-ensure-bazelisk
        - test-gerrit-setup
        - test-gerrit-plugin-build
        - test-gerrit-build-master
        - test-gerrit-build-stable-3.8
        - test-gerrit-build-stable-3.9
        - test-gerrit-build-stable-3.10
        - test-gitiles-build-master
        - test-install-build-essential
