- name: Prepare plugin repos for gerrit
  prepare_gerrit_repos:
    gerrit_project_mapping: "{{ gerrit_project_mapping }}"
    gerrit_project_name: "{{ gerrit_project_name }}"
    gerrit_root: "{{ gerrit_root }}"
    zuul_dict: "{{ zuul }}"
